### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by kliegeois** [sandialabs/GenTen#1]
The README seems outdated:

> Kokkos for perfomance portable shared memory parallelism. Genten bundles a clone of the Kokkos source using git subtree for use with inline builds (see below), which is generally kept up to date with the current Kokkos master branch (which corresponds to Kokkos releases). This is the only version of Kokkos that is guaranteed to work with Genten (however later versions or the develop branch may work).
A C++14 standard-compliant compiler. In principle, any C++14 compiler supported by Kokkos should work, (...)

Kokkos latest releases require a C++17 compliant compiler.

An alternative to updating the README to mirror Kokkos compiler requirements every time they changed would be to cite that webpage directly in the README https://kokkos.org/kokkos-core-wiki/requirements.html .

**Comment by etphipp** [comment]
Congratulations on creating the first issue for the new GenTen repo!

The whole README is out of date as most of the build instructions are no longer correct.  But this is a good suggestion.

**Comment by etphipp** [comment]
Btw, how did you discover the new repo?

**Comment by kliegeois** [comment]
The fact that you made the repo public appeared at the top of my GitHub homepage feed this morning 😃 .

**Comment by etphipp** [comment]
I've updated the README extensively for this and other changes.  Have a look if you are so inclined.  There is a lot more I need to do in providing actual documentation on how to build and run GenTen.

**Comment by kliegeois** [comment]
Thanks for the update!
