### ISSUE TITLE
feature request: sparse submanifold reconstruction

### ISSUE THREAD

**Issue by scott-uses-git** [sandialabs/GenTen#6]
Hello,

I was wondering if you might consider adding a method for reconstructing the input tensor which only computes the non-zero elements. For my application, reconstructing the entire tensor is unnecessary and very slow due to the size of the full tensor. As far as I can tell, the current genten sparse reconstruction method will reconstruct the entire tensor, then throw away the zeroes. What I'm asking for is a method that only computes reconstructions for elements that are nonzero in the observed input data.

I implemented the calculation in R, but its pretty slow due to all the indexing and would be much better in C++
```
compute_ssm_fit <- function(model_fit, input_data) {
  g <- model_fit$ktensor$weights
  X <- model_fit$factors
  m <- length(X)
  
  I <- as.matrix(input_data[, 1:m])
  y <- input_data[[m+1]]
  
  yk <-
    matrix(
      0, nrow(I), length(g),
      dimnames=list(NULL, paste0("yk", 1:length(g)))
    )
  
  for (i in 1:nrow(yk)) {
    for (k in 1:ncol(yk)) {
      yk[i, k] <- g[k]
      for (j in 1:m) {
        yk[i, k] <- yk[i, k] * X[[j]][I[i, j], k]
      }
    }
  }

  # total
  yt <- rowSums(yk)
  # residuals
  yr <- y - yt
  
  input_data %>%   
    bind_cols(yt=yt, yr=yr) %>% 
    bind_cols(yk) 
}
```

The name "sparse submanifold" comes from field of doing convolutions on sparse data - see this article: https://paperswithcode.com/method/submanifold-convolutions

**Comment by etphipp** [comment]
Seems reasonable.  I'll work on adding that this week.

**Comment by scott-uses-git** [comment]
Awesome, thanks!

There's one other reconstruction feature that would be useful for me: computing the individual contributions to the reconstruction for each factor. This would correspond to the `yk` matrix in my R code. The total reconstruction `yt` is computed as the row sums of this matrix. This might be outside the scope of general usage though.

**Comment by etphipp** [comment]
The ability to compute a sparse reconstruction based on the nonzero pattern has been added.  For the CLI, the option is:
```
"  --sparse-nonzero-reconstruction <string>  output file name for saving the tensor reconstruction as a sparse tensor using only nonzeros of the original sparse tensor (only for sparse input)"
```
It can also be called from within the python interface through a new Sptensor constructor:
```
Sptensor recon(x,u)
```
where `x` is the original sparse tensor and `u` is a Ktensor.

Sorry this took a while.  Getting it to work with distributed parallelism was a bigger task than I realized.

As for the second feature, you should be able to do this now using the python interface.  Just make form a new rank-1 Ktensor from each factor matrix component and call the above sparse reconstruction.  This is fairly easy with pyttb, and there are routines to convert between pyttb sptensor/ktensor and pygenten Sptensor/Ktensor.

**Comment by scott-uses-git** [comment]
Awesome, thanks!!

**Comment by scott-uses-git** [comment]
closing
